FROM postgres:16-alpine

# Set environment variables
ENV POSTGRES_DB=internships
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Create data directory
RUN mkdir -p /var/lib/postgresql/data

# Expose PostgreSQL port
EXPOSE 5432

# Start PostgreSQL
CMD ["postgres"]
